name: Auto Deploy to Server

on:
  push:
    branches:
      - main  # Запускать деплой при каждом пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v2

      # Добавление SSH ключа и добавление сервера в known_hosts
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_FOR_SERVER }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # Завершение старого процесса
      - name: Stop old Java process
        run: |
          ssh root@49.13.2.245 "pkill -f 'java -jar' || true"
          
      # Обновление репозитория на сервере через git pull
      - name: Update project from GitHub on server
        run: |
          ssh root@49.13.2.245 "cd /root/CryptoAdvisor && git pull origin main"

      # Копирование нового JAR файла на сервер
      - name: Copy new JAR to server
        run: |
          scp target/Cryptoadvises1.1-1.0-SNAPSHOT.jar root@49.13.2.245:/root/CryptoAdvisor/target/

      # Запуск новой версии приложения
      - name: Start new application
        run: |
          ssh root@49.13.2.245 "nohup java -jar /root/CryptoAdvisor/target/Cryptoadvises1.1-1.0-SNAPSHOT.jar &"
