name: Auto Deploy to Server

on:
  push:
    branches:
      - main  # Запускать деплой при каждом пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v2

      # Добавление SSH ключа и добавление сервера в known_hosts
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_FOR_SERVER }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # Завершение всех процессов Java
      - name: Stop old Java process
        run: |
          ssh root@49.13.2.245 "ps aux | grep '[j]ava -jar' | awk '{print \$2}' | xargs -r kill -9"

      # Обновление репозитория на сервере через git pull
      - name: Update project from GitHub on server
        run: |
          ssh root@49.13.2.245 "cd /root/CryptoAdvisor && git pull origin main"

      # Выполнение Maven сборки (clean package)
      - name: Build project using Maven
        run: |
          ssh root@49.13.2.245 "cd /root/CryptoAdvisor && mvn clean package"

      # Убедись, что JAR был пересобран и находится в правильной директории
      - name: Verify that JAR is present
        run: |
          ssh root@49.13.2.245 "ls -lh /root/CryptoAdvisor/target/"

      # Запуск новой версии приложения с логами
      - name: Start new application
        run: |
          ssh root@49.13.2.245 "nohup java -jar /root/CryptoAdvisor/target/Cryptoadvises1.1-1.0-SNAPSHOT.jar > /root/CryptoAdvisor/target/app.log 2>&1 &"

      # Проверка, что приложение запущено и логи созданы
      - name: Check application logs
        run: |
          ssh root@49.13.2.245 "tail -n 20 /root/CryptoAdvisor/target/app.log"




