name: Auto Deploy to Server

on:
  push:
    branches:
      - main  # Запускать деплой при каждом пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v2

      # Добавление SSH ключа для подключения к серверу
      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_FOR_SERVER }}  # Используй свой секретный ключ
          known_hosts: 49.13.2.245  # IP адрес твоего сервера

      # Завершение старого процесса
      - name: Stop old Java process
        run: |
          ssh root@49.13.2.245 "pkill -f 'java -jar' || true"

      # Копирование нового JAR файла на сервер
      - name: Copy new JAR to server
        run: |
          scp target/Cryptoadvises1.1-1.0-SNAPSHOT.jar root@49.13.2.245:root/CryptoAdvisor

      # Запуск новой версии приложения
      - name: Start new application
        run: |
          ssh root@49.13.2.245 "nohup java -jar /root/CryptoAdvisor/target/Cryptoadvises1.1-1.0-SNAPSHOT.jar &"
